kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redmine-build-folder
  namespace: aesa-planifica
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem

