apiVersion: v1
kind: Secret
metadata:
  name: aesa-pull-bot-secret
  namespace: aesa-planifica
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJuZXctYWVzYS1yZWdpc3RyeS1xdWF5LWxvY2FsLXF1YXkuYXBwcy5vY3BtZ20uYXZpYWNpb24uZm9tZW50by5lcyI6IHsKICAgICAgImF1dGgiOiAiWVdWellTdGphV05rT2s1TFJVMVZOMHhLUjFKVE4wUlVObGN4VjFjeFdFUklVVGRUUjB0RldrRlFWREpRTjFaR09GSlVSVXRhU3pFelR6Tk5VMEpWTUUxRFRGVkpTVmxFTmtVPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
